theme: jekyll-theme-cayman

title: Tommy Rosario

description: front-end developer extraordinaire 

navbar-links:
  GitHub: "https://github.com/tjrosario"
  LinkedIn: "https://www.linkedin.com/in/tommy-rosario-65771711"
